agro:
  notification:
    requests: "agro.notification.requests"
    responses: "agro.notification.responses"
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kabopok@gmail.com
    password: "juba gxjk tqum vumx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          debug: true
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}
    consumer:
      group-id: notificationServiceGroup
  #    consumer:
  #      enable-auto-commit: true
server:
  port: ${SERVER_PORT}


